[project]
name = "faastapi"
version = "0.1.0"
description = "Learning API development"
readme = "README.md"
authors = [
    { name = "zephyr" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "bcrypt==4.0.1",
    "passlib[bcrypt]>=1.7.4",
    "psycopg2>=2.9.13",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.54",
    "python-jose[cryptography]>=3.5.0",
    "alembic>=1.20.0",
]

[project.scripts]
faastapi = "faastapi:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
